"""
plot_nak_combined.jl
Create combined Li/Na/K figures from saved data.

Outputs:
  fig/nak_bands_qp.pdf  — two-panel Na+K band structure (for PRL main text)
  fig/delta_K_all.pdf   — Δ(K) for Li/Na/K (for appendix / future use)

Requires (generated by sodium/gen_band_data.jl and potassium/freq_correction.jl):
  sodium/na_band_data.jls, sodium/na_delta_data.jls
  potassium/k_band_data.jls, potassium/k_delta_data.jls
Li Δ(K) is computed analytically (no saved data needed).

Usage: julia --project=. notes/plot_nak_combined.jl
"""

if "--dry-run" in ARGS
    println("[dry-run] notes/plot_nak_combined.jl")
    println("  Plots: Na+K full BZ bands, Δ(K) for all 6 elements")
    println("  Reads: {li,na,k,mg,al,si}_delta_data.jls, {na,k}_band_data.jls")
    println("  Saves: notes/fig/nak_bands_qp.pdf, notes/fig/delta_K_all.pdf")
    exit(0)
end

using Serialization
using Plots

Ha_to_eV = 27.211386245988
figdir = joinpath(@__DIR__, "fig")
mkpath(figdir)

# Load saved data (Li, Na, K)
li_delta = deserialize(joinpath(@__DIR__, "..", "lithium", "li_delta_data.jls"))
na = deserialize(joinpath(@__DIR__, "..", "sodium", "na_band_data.jls"))
k = deserialize(joinpath(@__DIR__, "..", "potassium", "k_band_data.jls"))
na_delta = deserialize(joinpath(@__DIR__, "..", "sodium", "na_delta_data.jls"))
k_delta = deserialize(joinpath(@__DIR__, "..", "potassium", "k_delta_data.jls"))

# ══════════════════════════════════════════════════════════════════════════════
# Figure 1: Na + K band structures (two-panel, for PRL main text)
# ══════════════════════════════════════════════════════════════════════════════

function plot_bands!(p, data; show_ylabel=true)
    for n in 1:data["n_bands"]
        ks_eV = (data["eigenvalues"][:, n, 1] .- data["εF"]) .* Ha_to_eV
        qp_eV = (data["eqp"][:, n, 1] .- data["εF"]) .* Ha_to_eV
        lb_ks = n == 1 ? "KS" : ""
        lb_qp = n == 1 ? "QP" : ""
        plot!(p, data["kdistances"], ks_eV; color=:blue, lw=2, label=lb_ks)
        plot!(p, data["kdistances"], qp_eV; color=:red, lw=2, ls=:dash, label=lb_qp)
    end
    hline!(p, [0.0]; color=:gray, ls=:dot, label="", lw=1)
    vline!(p, data["tick_distances"]; color=:gray, lw=0.5, label="")
    plot!(p; xticks=(data["tick_distances"], data["tick_labels"]))
    xlims!(p, data["kdistances"][1], data["kdistances"][end])
    ylims!(p, -4.5, 6.0)
end

p_na = plot(ylabel="Energy (eV)", xlabel="", legend=:topright,
    framestyle=:box, title="Na", titleloc=:left, titlefontsize=11,
    bottom_margin=-3Plots.mm, xformatter=_ -> "")
plot_bands!(p_na, na)

p_k = plot(ylabel="Energy (eV)", xlabel="", legend=:topright,
    framestyle=:box, title="K", titleloc=:left, titlefontsize=11,
    top_margin=-3Plots.mm)
plot_bands!(p_k, k)

p_bands = plot(p_na, p_k; layout=(2, 1), size=(400, 550),
    margin=0Plots.mm)

savefig(p_bands, joinpath(figdir, "nak_bands_qp.pdf"))
println("Saved → fig/nak_bands_qp.pdf")

# ══════════════════════════════════════════════════════════════════════════════
# Figure 2: Δ(K) comparison (all elements)
# ══════════════════════════════════════════════════════════════════════════════

mg_delta = deserialize(joinpath(@__DIR__, "..", "magnesium", "mg_delta_data.jls"))
al_delta = deserialize(joinpath(@__DIR__, "..", "aluminum", "al_delta_data.jls"))
si_delta = deserialize(joinpath(@__DIR__, "..", "silicon", "si_delta_data.jls"))

p_delta = plot(xlabel="K (Bohr⁻¹)", ylabel="Δ(K)",
    legend=:topright, framestyle=:box, size=(600, 400))

for (data, color, ls, label) in [
    (k_delta,  :red,      :solid,  "K"),
    (li_delta, :green,    :solid,  "Li"),
    (na_delta, :blue,     :dash,   "Na"),
    (mg_delta, :brown,    :dash,   "Mg"),
    (al_delta, :purple,   :dot,    "Al"),
    (si_delta, :orange,   :dot,    "Si"),
]
    Kg = data["K_grid"]
    idx = Kg .<= 10.0
    plot!(p_delta, Kg[idx], data["delta_total"][idx];
        color=color, lw=2, ls=ls, label=label)
end

savefig(p_delta, joinpath(figdir, "delta_K_all.pdf"))
println("Saved → fig/delta_K_all.pdf")
