"""
plot_pbe_bands.jl
Six-panel figure comparing LDA vs PBE band structures with EFT QP correction.
Demonstrates robustness of the frequency correction to XC functional and PSP choice.

Outputs:
  fig/pbe_bands_comparison.pdf — 2×3 panel:
    Top:    Na, K, Ca   (different Z_val)
    Bottom: Mg, Al, Si  (same Z_val)

Requires (generated by <element>/run_ks.jl, run_ks_pbe.jl, freq_correction_pbe.jl):
  KS data:     <element>/<elem>_ks_data.jld2, <elem>_pbe_ks_data.jld2
  QP data:     <element>/<elem>_pbe_qp_data.jld2

Usage: julia --project=. notes/plot_pbe_bands.jl
"""

if "--dry-run" in ARGS
    println("[dry-run] notes/plot_pbe_bands.jl")
    println("  Plots: 6-panel LDA vs PBE band comparison")
    println("  Reads: {na,k,ca,mg,al,si}_{ks,pbe_ks,pbe_qp}_data.jld2")
    println("  Saves: notes/fig/pbe_bands_comparison.pdf")
    exit(0)
end

using JLD2
using PyPlot

Ha_to_eV = 27.211386245988
figdir = joinpath(@__DIR__, "fig")
mkpath(figdir)

# ── Load helpers ──────────────────────────────────────────────────────────────

"""
Try multiple key names and return the first that exists in the dict.
"""
function getany(d, keys...)
    for k in keys
        haskey(d, k) && return d[k]
    end
    error("None of these keys found: $(keys)")
end

"""
Load LDA+PBE band data for one element from JLD2 pipeline files.

Returns a NamedTuple with:
  lda_eigenvalues, lda_eqp, lda_εF, lda_kdistances, lda_tick_distances, lda_tick_labels, lda_n_bands
  pbe_eigenvalues, pbe_eqp, pbe_εF, pbe_kdistances, pbe_tick_distances, pbe_tick_labels, pbe_n_bands
  conduction_band (for diff-Zion elements; 0 for same-Zion)
"""
function load_element(elemdir, prefix; has_conduction_band=false)
    ks_lda_file  = joinpath(elemdir, "$(prefix)_ks_data.jld2")
    ks_pbe_file  = joinpath(elemdir, "$(prefix)_pbe_ks_data.jld2")
    pbe_qp_file  = joinpath(elemdir, "$(prefix)_pbe_qp_data.jld2")

    ks_lda = load(ks_lda_file)
    ks_pbe = load(ks_pbe_file)
    pbe_qp = load(pbe_qp_file)

    # LDA eigenvalues and plotting info from KS data
    lda_eigenvalues = ks_lda["eigenvalues_array"]
    lda_kdistances  = ks_lda["kdistances"]
    lda_tick_dist   = ks_lda["tick_distances"]
    lda_tick_labels = ks_lda["tick_labels"]
    lda_εF          = ks_lda["εF"]
    lda_n_bands     = size(lda_eigenvalues, 2)

    # PBE eigenvalues and plotting info from KS data
    pbe_eigenvalues = ks_pbe["eigenvalues_array"]
    pbe_kdistances  = ks_pbe["kdistances"]
    pbe_tick_dist   = ks_pbe["tick_distances"]
    pbe_tick_labels = ks_pbe["tick_labels"]
    pbe_εF          = ks_pbe["εF"]
    pbe_n_bands     = size(pbe_eigenvalues, 2)

    # QP arrays from PBE QP data (key names vary across elements)
    lda_eqp = getany(pbe_qp, "eqp_arr_lda", "lda_eqp_arr")
    pbe_eqp = getany(pbe_qp, "eqp_arr_pbe", "pbe_eqp_arr")

    # Conduction band index for diff-Zion elements
    cond = 0
    if has_conduction_band
        cond = Int(getany(pbe_qp, "conduction_band", "pbe_conduction_band"))
    end

    return (;
        lda_eigenvalues, lda_eqp, lda_εF, lda_kdistances,
        lda_tick_distances=lda_tick_dist, lda_tick_labels, lda_n_bands,
        pbe_eigenvalues, pbe_eqp, pbe_εF, pbe_kdistances,
        pbe_tick_distances=pbe_tick_dist, pbe_tick_labels, pbe_n_bands,
        conduction_band=cond,
    )
end

# ── Load all elements ─────────────────────────────────────────────────────────
basedir = joinpath(@__DIR__, "..")

na    = load_element(joinpath(basedir, "sodium"),    "na"; has_conduction_band=true)
kdata = load_element(joinpath(basedir, "potassium"), "k";  has_conduction_band=true)
ca    = load_element(joinpath(basedir, "calcium"),   "ca"; has_conduction_band=true)
mg    = load_element(joinpath(basedir, "magnesium"), "mg")
al    = load_element(joinpath(basedir, "aluminum"),  "al")
si    = load_element(joinpath(basedir, "silicon"),   "si")

# ── Plotting helpers ──────────────────────────────────────────────────────────

function plot_same_zion!(ax, data, title_str; ylims=(-12, 6), n_plot=nothing,
                        tick_range=nothing)
    kd_lda = data.lda_kdistances
    kd_pbe = data.pbe_kdistances
    εF_lda = data.lda_εF
    εF_pbe = data.pbe_εF

    td_all = data.lda_tick_distances
    tl_all = data.lda_tick_labels

    # Optionally trim to a subset of ticks (e.g. 1:5)
    if !isnothing(tick_range)
        td = td_all[tick_range]
        tl = tl_all[tick_range]
        xlo, xhi = td[1], td[end]
        idx_lda = findall(x -> xlo - 1e-8 <= x <= xhi + 1e-8, kd_lda)
        idx_pbe = findall(x -> xlo - 1e-8 <= x <= xhi + 1e-8, kd_pbe)
    else
        td = td_all
        tl = tl_all
        idx_lda = eachindex(kd_lda)
        idx_pbe = eachindex(kd_pbe)
        xlo, xhi = kd_lda[1], kd_lda[end]
    end

    n_bands = isnothing(n_plot) ? data.lda_n_bands : n_plot

    # LDA bands: solid
    for n in 1:n_bands
        ks_eV = (data.lda_eigenvalues[idx_lda, n, 1] .- εF_lda) .* Ha_to_eV
        qp_eV = (data.lda_eqp[idx_lda, n, 1] .- εF_lda) .* Ha_to_eV
        lb_ks = n == 1 ? "LDA KS" : ""
        lb_qp = n == 1 ? "LDA QP" : ""
        ax.plot(kd_lda[idx_lda], ks_eV; color="blue", lw=1.5, label=lb_ks)
        ax.plot(kd_lda[idx_lda], qp_eV; color="red", lw=1.5, label=lb_qp)
    end

    # PBE bands: dashed, slightly thicker
    for n in 1:n_bands
        ks_eV = (data.pbe_eigenvalues[idx_pbe, n, 1] .- εF_pbe) .* Ha_to_eV
        qp_eV = (data.pbe_eqp[idx_pbe, n, 1] .- εF_pbe) .* Ha_to_eV
        lb_ks = n == 1 ? "PBE KS" : ""
        lb_qp = n == 1 ? "PBE QP" : ""
        ax.plot(kd_pbe[idx_pbe], ks_eV; color="blue", lw=2.0, ls="--", alpha=0.7, label=lb_ks)
        ax.plot(kd_pbe[idx_pbe], qp_eV; color="red", lw=2.0, ls="--", alpha=0.7, label=lb_qp)
    end

    # Decorations
    ax.axhline(0.0; color="gray", ls=":", lw=0.8)
    for d in td
        ax.axvline(d; color="gray", lw=0.4)
    end
    ax.set_xticks(td)
    ax.set_xticklabels(tl)
    ax.set_xlim(xlo, xhi)
    ax.set_ylim(ylims...)
    ax.set_title(title_str; loc="left", fontsize=10)
end

function plot_diff_zion!(ax, data, title_str; ylims=(-4.5, 6), n_plot_lda=nothing)
    kd_lda = data.lda_kdistances
    kd_pbe = data.pbe_kdistances
    εF_lda = data.lda_εF
    εF_pbe = data.pbe_εF

    n_lda = isnothing(n_plot_lda) ? data.lda_n_bands : n_plot_lda
    cond = data.conduction_band

    # LDA bands (all): solid
    for n in 1:n_lda
        ks_eV = (data.lda_eigenvalues[:, n, 1] .- εF_lda) .* Ha_to_eV
        qp_eV = (data.lda_eqp[:, n, 1] .- εF_lda) .* Ha_to_eV
        lb_ks = n == 1 ? "LDA KS" : ""
        lb_qp = n == 1 ? "LDA QP" : ""
        ax.plot(kd_lda, ks_eV; color="blue", lw=1.5, label=lb_ks)
        ax.plot(kd_lda, qp_eV; color="red", lw=1.5, label=lb_qp)
    end

    # PBE conduction band only: dashed
    for n in cond:min(cond+n_lda-1, data.pbe_n_bands)
        ks_eV = (data.pbe_eigenvalues[:, n, 1] .- εF_pbe) .* Ha_to_eV
        qp_eV = (data.pbe_eqp[:, n, 1] .- εF_pbe) .* Ha_to_eV
        lb_ks = n == cond ? "PBE KS" : ""
        lb_qp = n == cond ? "PBE QP" : ""
        ax.plot(kd_pbe, ks_eV; color="blue", lw=2.0, ls="--", alpha=0.7, label=lb_ks)
        ax.plot(kd_pbe, qp_eV; color="red", lw=2.0, ls="--", alpha=0.7, label=lb_qp)
    end

    # Decorations
    ax.axhline(0.0; color="gray", ls=":", lw=0.8)
    td = data.lda_tick_distances
    for d in td
        ax.axvline(d; color="gray", lw=0.4)
    end
    ax.set_xticks(td)
    ax.set_xticklabels(data.lda_tick_labels)
    ax.set_xlim(kd_lda[1], kd_lda[end])
    ax.set_ylim(ylims...)
    ax.set_title(title_str; loc="left", fontsize=10)
end

# ══════════════════════════════════════════════════════════════════════════════
# 2×3 figure: top = different Zion (Na, K, Ca), bottom = same Zion (Mg, Al, Si)
# ══════════════════════════════════════════════════════════════════════════════

fig, axes = subplots(2, 3; figsize=(10.0, 6.0))

# Top row: different Zion
plot_diff_zion!(axes[1,1], na, "Na (1→9)"; ylims=(-4.5, 4.0), n_plot_lda=4)
plot_diff_zion!(axes[1,2], kdata, "K (1→9)"; ylims=(-3.0, 3.0), n_plot_lda=4)
plot_diff_zion!(axes[1,3], ca, "Ca (2→10)"; ylims=(-5.0, 4.0), n_plot_lda=4)

# Bottom row: same Zion
plot_same_zion!(axes[2,1], mg, "Mg (2=2)"; ylims=(-8.0, 6.0), n_plot=4,
                tick_range=1:5)
plot_same_zion!(axes[2,2], al, "Al (3=3)"; ylims=(-13.0, 8.0), n_plot=4)
plot_same_zion!(axes[2,3], si, "Si (4=4)"; ylims=(-13.0, 8.0), n_plot=5)

# Labels
axes[1,1].set_ylabel("Energy (eV)")
axes[2,1].set_ylabel("Energy (eV)")

# Legend on first panel only
axes[1,1].legend(loc="upper right", framealpha=0.9, fontsize=6, ncol=2)

tight_layout()
savefig(joinpath(figdir, "pbe_bands_comparison.pdf"))
println("Saved → fig/pbe_bands_comparison.pdf")
close(fig)

println("\n=== Done ===")
